---
project: 
  type: website
  output-dir: "." 
website:
  title: "Emily Peters"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: DANL 310
        menu:
          - text: R Basics
            href: 310_files/danl-310-quarto-r.qmd
      - text: DANL 320
        menu:
          - text: Python Basics
            href: 320_files/danl-320-python-basic.ipynb
          - text: Seaborn
            href: 320_files/seaborn_basics.ipynb
          - text: Pandas
            href: 320_files/pandas_basics.ipynb
    right: 
      - text: Blog
        href: blog-listing.qmd
      
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Emily Peters, 2025"
format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly # darkly cyborg slate solar superhero
    mainfont: system-ui
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html
