project:
  type: website
  output-dir: "."

website:
  title: "Emily Peters"
  navbar:
    pinned: true
    left:
      - text: R Project
        href: project_files/project.qmd
      - text: Python Data Analysis
        menu:
          - text: Python Basics Lecture
            href: basic-python-intro.ipynb
          - text: Python Basics HW1 Summary
            href: hw1-python-basics.ipynb
      - text: Blog
        href: blog-listing.qmd
      - text: DANL 210 Python Project
        href: danl210_project4.ipynb
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Emily Peters, 2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
   
