---
title: "Lecture 3 - 1/27/25"
subtitle: "DANL 310: ggplot Review"
author: 
  - name: YOUR NAME
  - name: YOUR COWORKER 1
date: last-modified #YYYY-MM-DD

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true #table of contents
    number-sections: true
    code-fold: show       # https://quarto.org/docs/output-formats/html-code.html  
    code-tools: true      # https://quarto.org/docs/reference/cells/cells-jupyter.html
    highlight-style: atom-one # atom-one tango espresso
    
    
#code chunck shortcut: alt + ctrl + i
---

```{r}
library(gapminder)
gapminder <- gapminder::gapminder
```

```{r}
library(skimr)
skim(gapminder)
```

```{r}
library(tidyverse)
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point() 
```

```{r}
p + 
  geom_point() + 
  geom_smooth()
```

```{r}
#assign color to a variable gives different colors for each different value in that variable
p1 <-  ggplot(data = gapminder,
             mapping = aes(x = gdpPercap, y = lifeExp,
                           color = continent))
```

```{r}
p1 + geom_point() +
  geom_smooth(method = 'lm')
```

```{r}
p2 <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap, y = lifeExp))
```

```{r}
p2 + geom_point(color = "purple") +
     geom_smooth(color = "red", method = "loess", se = F, size = 8)
#other argument: alpha = <number between 0 & 1 excluding>
#size - thickness of points or line
```

```{r}
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))

p + geom_point(color = "purple") +
    geom_smooth(method = "loess") 

p + geom_point(alpha = 0.3) +
    geom_smooth(color = "orange", se = F, size = 8, method = "lm") 
```

```{r}
p + geom_point(alpha = 0.3) +
    geom_smooth(method = "gam") +
    scale_x_log10(labels = scales::dollar) +
    labs(x = "GDP Per Capita", 
         y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")
#scale_x_log10 - scales x by log10 (base 10 log of 1000 is 3)
#labs - labels
```

```{r}
# mapping aesthetics per geom
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap, y = lifeExp))

p + geom_point(mapping = aes(color = continent)) +
    geom_smooth(method = "loess")  +
    scale_x_continuous(trans = scales::log_trans())
#natural log ^
```

