---
title: "Transportation Accessibility Throughout New York State"
author: "Emily Peters"
editor: source
format: dashboard
---
# Data

```{r}
library(tidyverse)
library(ggthemes)
svi <- read.csv("C:\\Users\\peter\\OneDrive\\School_2024_25\\Spring25\\410\\SVI2022_NEWYORK_tract.csv")
svi2 <- svi |> 
  select(COUNTY, E_TOTPOP, E_NOVEH, E_UNEMP, E_NOHSDP, E_UNINSUR,
         E_AGE65, E_AGE17, E_DISABL, E_MINRTY, E_GROUPQ) |> 
  filter(COUNTY %in% c('Dutchess County', 'Lewis County', 'Livingston County', 'Madison County', 
                    'Nassau County', 'Ontario County',
                    'Schoharie County', 'Tioga County', 
                    'Ulster County', 'Wayne County', 'Wyoming County'),
         E_TOTPOP >= 0,
         E_NOVEH >= 0,
         E_UNEMP >= 0, 
         E_NOHSDP >= 0, 
         E_UNINSUR >= 0, 
         E_AGE65 >= 0, 
         E_AGE17 >= 0, 
         E_DISABL >= 0,
         E_MINRTY >= 0,
         E_GROUPQ >= 0) |> 
  group_by(COUNTY) |> 
  summarize(C_TOTPOP = sum(E_TOTPOP),
            C_NOVEH = sum(E_NOVEH),
            C_UNEMP = sum(E_UNEMP),
            C_NOHSDP = sum(E_NOHSDP),
            C_UNINSUR = sum(E_UNINSUR),
            C_AGE65 = sum(E_AGE65),
            C_AGE17 = sum(E_AGE17),
            C_DISABL = sum(E_DISABL),
            C_MINRTY = sum(E_MINRTY)) |> 
  mutate(RATING = c("Sufficient","Unideal","Sufficient","Sufficient",
                    "Good","Unideal","Unideal","Unideal","Good","Sufficient","Unideal"))
  
svi3 <- svi2 |> 
  mutate(NOVEH = C_NOVEH/C_TOTPOP,
         UNEMP = C_UNEMP/C_TOTPOP,
         NOHSDP = C_NOHSDP/C_TOTPOP,
         UNINSUR = C_UNINSUR/C_TOTPOP,
         AGE65 = C_AGE65/C_TOTPOP,
         AGE17 = C_AGE17/C_TOTPOP,
         DISABL = C_DISABL/C_TOTPOP,
         MINRTY = C_MINRTY/C_TOTPOP)

svi3_long <- svi3 |> 
  select(COUNTY, NOVEH, UNEMP, NOHSDP,
         UNINSUR, AGE65, AGE17,
         DISABL, MINRTY) |> 
  pivot_longer(cols = c('NOVEH', 'UNEMP', 'NOHSDP',
                        'UNINSUR', 'AGE65', 'AGE17',
                        'DISABL', 'MINRTY'),
               names_to = "PERC_TYPE",
               values_to = "PERC") 

```

```{r}
#| content: valuebox
#| title: "Total Population (All Counties)"

list(
  icon = "bar-chart",
  color = "info",
  value = sum(svi2$C_TOTPOP)
)

```

```{r}
#| content: valuebox
#| title: "Highest No Vehicle %"

highest_noveh <- svi3 |> 
  arrange(desc(NOVEH)) |> 
  filter(COUNTY == "Wyoming County")
  

list(
  icon = "car-front",
  color = "danger",
  value = highest_noveh$NOVEH
)

```

```{r}
#| content: valuebox
#| title: "Highest Unemployment %"

highest_unemp <- svi3 |> 
  arrange(desc(UNEMP)) |>
  filter(COUNTY == "Tioga County")

list(
  icon = "briefcase",
  color = "warning",
  value = highest_unemp$UNEMP
)

```

```{r}
#| content: valuebox
#| title: "Sufficient Counties Count"

counts <- svi2 |> 
  filter(RATING == "Sufficient") |> 
  count(RATING) |> 
  pull(n)  

list(
  icon = "bus-front",
  color = "secondary",
  value = counts
)

```

# Visualizations

```{r}
#| title: Populations of Each County
ggplot(data = svi2,
       mapping = aes(x = fct_reorder(COUNTY,
                                     C_TOTPOP),
                     y = C_TOTPOP))+
  geom_col(fill = 'steelblue4')+
  geom_text(aes(label = C_TOTPOP),
            size = 2.5,
            vjust = -.3)+
  labs(x = "",
       y = "County Population",
       title = "Population of Each County",
       subtitle = "Year: 2022")+
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   face = 'bold'))
```

```{r}
#| title: SVI Factor Percentages for Unideal Counties 
ggplot()+
  geom_line(data = svi3_long |> filter(COUNTY %in% c('Lewis County', 'Schoharie County', 'Tioga County', 
                                                     'Wyoming County')),
            mapping = aes(x = PERC_TYPE,
                          y = PERC,
                          group = COUNTY,
                          color = COUNTY),
            linewidth = 1.5)+
  geom_point(data = svi3_long |> filter(COUNTY %in% c('Lewis County', 'Ontario County', 'Schoharie County', 'Tioga County', 
                                                      'Wyoming County')),
             mapping = aes(x = PERC_TYPE,
                           y = PERC))+
  scale_color_viridis_d()+
  labs(x = 'Social Vulnerability Factor',
       y = 'Percentage',
       title = 'Social Vulnerability Percentages',
       subtitle = "Counties Classified Under 'Unideal' Public Transportation Services")+
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   face = 'bold'),
        title = element_text(face = 'bold'))
```

```{r}
#| title: SVI Factor Percentages for Sufficient Counties
ggplot(data = svi3_long |> filter(COUNTY %in% c('Dutchess County', 'Livingston County', 'Madison County', 'Wayne County')),
       mapping = aes(x = PERC_TYPE,
                     y = PERC,
                     group = COUNTY))+
  geom_line(aes(color = COUNTY),
            linewidth = 1.5)+
  geom_point()+
  scale_color_tableau()+
  labs(x = 'Social Vulnerability Factor',
       y = 'Percentage',
       title = 'Social Vulnerability Percentages',
       subtitle = "Counties Classified Under 'Sufficient' Public Transportation Services")+
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   face = 'bold'),
        title = element_text(face = 'bold'))

```

```{r}
#| title: SVI Factor Percentages for Good Counties
ggplot(data = svi3_long |> filter(COUNTY %in% c('Ontario County','Nassau County', 'Ulster County')),
       mapping = aes(x = PERC_TYPE,
                     y = PERC,
                     group = COUNTY))+
  geom_line(aes(color = COUNTY),
            linewidth = 1.5)+
  geom_point()+
  scale_color_manual(values = c('grey30', 'darkgreen', 'purple4'))+
  labs(x = 'Social Vulnerability Factor',
       y = 'Percentage',
       title = 'Social Vulnerability Percentages',
       subtitle = "Counties Classified Under 'Good' Public Transportation Services")+
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   face = 'bold'),
        title = element_text(face = 'bold'))
```

